packages:
  - "packages/shared-types"
  - "packages/router"
  - "packages/event-system"
  - "packages/api-contract"
  - "packages/auth-agent"
  - "packages/content-agent"
  - "packages/library-agent"
  - "packages/emotion-agent"
  - "packages/commerce-agent"
  - "packages/insights-agent"
  - "packages/smart-home-agent"
  - "packages/voice-synthesis"
  - "packages/universal-agent"
