export { EventSystem, EventSystemConfig } from './EventSystem';
export { EventPublisher } from './EventPublisher';
export { EventSubscriber } from './EventSubscriber';
export { EventStore } from './EventStore';
export { CloudEvent, EventType, EventSource, EventPublisherConfig, EventSubscription, EventHandler, EventReplayConfig, EventCorrelation, EventMetrics, EventStore as IEventStore, EventQueryCriteria, EventDebugInfo, EventProcessingStep, EventError, EventPerformanceMetrics, EventValidationSchema } from './types';
export { OpenTelemetryTracer, TracingConfig } from './monitoring/OpenTelemetryTracer';
export { MetricsCollector, MetricsConfig, SystemMetrics, AlertRule } from './monitoring/MetricsCollector';
export declare const createEventId: () => any;
export declare const createCorrelationId: () => any;
export declare const isSystemEvent: (eventType: EventType) => boolean;
export declare const isPrivacyEvent: (eventType: EventType) => boolean;
export declare const isStoryEvent: (eventType: EventType) => boolean;
export declare const isSmartHomeEvent: (eventType: EventType) => boolean;
export declare const validateCloudEvent: (event: any) => event is CloudEvent;
export declare const tokenizePII: (data: any) => any;
