import OpenAI from 'openai';
import { Logger } from 'winston';
import { ContentSafetyRequest, QualityAssessmentResult } from '../types';
export declare class QualityAssuranceEngine {
    private openai;
    private logger;
    constructor(openai: OpenAI, logger: Logger);
    initialize(): Promise<void>;
    assessQuality(content: string, request: ContentSafetyRequest): Promise<QualityAssessmentResult>;
    private assessNarrativeCoherence;
    private assessAgeAppropriateness;
    private assessEducationalValue;
    private assessEmotionalResonance;
    private assessCreativity;
    private predictParentRating;
    private hasStoryBeginning;
    private hasStoryMiddle;
    private hasStoryEnd;
    private hasCharacterDevelopment;
    private hasLogicalFlow;
    private assessVocabularyComplexity;
    private assessSentenceComplexity;
    private assessThemeAppropriateness;
    private assessLengthAppropriateness;
    private hasLearningObjective;
    private hasPositiveValues;
    private hasProblemSolving;
    private hasCharacterGrowth;
    private hasRealWorldConnection;
    private encouragesCriticalThinking;
    private hasEmotionalDepth;
    private hasRelatableCharacters;
    private hasEmotionalJourney;
    private hasEmpathyBuilding;
    private hasEmotionalResolution;
    private hasOriginalIdeas;
    private hasImaginativeElements;
    private hasUnexpectedTwists;
    private hasCreativeLanguage;
    private hasUniqueCharacters;
    private calculateOverallQuality;
    private generateAssessmentDetails;
    private getStrengthMessage;
    private getWeaknessMessage;
    private getSuggestionMessage;
    private isComplexWord;
    private getMaxComplexityRatio;
    private getMaxWordsPerSentence;
    private getInappropriateThemes;
    private getIdealWordCount;
    private getEmotionalComplexityMultiplier;
    private assessContentSafety;
    private assessPositiveValues;
    private hasIntroduction;
    private hasMainContent;
    private hasConclusion;
    private hasCoherentFlow;
    healthCheck(): Promise<boolean>;
}
//# sourceMappingURL=QualityAssuranceEngine.d.ts.map